### ISSUE TITLE
Question: Relationship to ldapjs – wrapper, fork or re-implementation?

### ISSUE THREAD

**Issue by Philzen** [ldapts/ldapts#116]
We're currently building an LDAP integration in a RedwoodJS project, and after an initial successful implementation with [node-ldapauth-fork](https://github.com/vesse/node-ldapauth-fork) (which wraps ldapjs with some syntactic sugar) i stumbled across ldapts in a medium-article.

Now i'm comtemplating whether to switch to ldapts, as the API looks much cleaner and more appealing at first glance, and it would be a good fit for the existing TS project ecosystem.

According to your README.md it's "based on" ldapjs. However i could not to find it as a dependency in the package.json. So is this technically a re-implementation or TS-based fork (and if yes, at which version of ldapjs did it happen)?

**Comment by jgeurts** [comment]
Hi, thanks for your interest! Generally speaking, I'd call this project a re-implementation using typescript and modern coding conventions.

When this project started, ldapjs was pretty much dead without a maintainer. There were a number of outstanding issues that were not addressed. So I started this project, basing the original api surface and a fair amount of the underlying logic from ldapjs. The code was modernized, the tests hit actual ldap servers, and a lot of issues were addressed. 

This project started around Nov 2018, so the ldapjs code would have been around v1.0.2, give or take. There has since been a restructuring of maintainers over there and it sounds like they're moving the project again. 

Hope that helps and please let me know if you have more questions!
