### ISSUE TITLE
wrong dependencies/dev dependencies

### ISSUE THREAD

**Issue by Dudek-AMS** [ldapts/ldapts#153]
This packages lists some packages as dependecy, which should be a dev depency.

likes any @types dependency or debugger

**Comment by jgeurts** [comment]
Thanks for reaching out! The @types/asn1 package is exported because some of those types are exposed by ldapts signatures. The debug library is used for logging throughout the application. I have, however moved the @types/uuid package to devDependencies, as those types are not exposed by ldapts. Things should be updated with v7.1.0
