### ISSUE TITLE
The `sizeLimit` option is limiting result to N-1 items

### ISSUE THREAD

**Issue by ma-zal** [ldapts/ldapts#17]
It looks like when `sizeLimit` option is defined, the library is returning N-1 items only (one item is missing). Example: When I selected `sizeLimit=2`, one item (user) were been returned only.

Tested on:  LDAPTS version: 1.4.2, LDAP server: Microsoft Active LDAP

---
Note: When sizeLimit is not defined, the real limit looks like 100 items. The default value is not documented in source code. But I am not sure if this limit is caused by lib, or it is default value somewhere in AD LDAP server - so adding this info as minor information only.

**Comment by jgeurts** [comment]
Hi! There can be some confusion with `sizeLimit` and `pageSize`. `sizeLimit` controls how many records should be returned regardless of paging. 

If `pageSize` is not defined, then it will default to `100` unless `sizeLimit` is defined in which case `pageSize` will equal `sizeLimit - 1`. This is due to the [RFC](https://tools.ietf.org/html/rfc2696#section-3) where servers should ignore the paging control if `pageSize >= sizeLimit`.

With the next release, I'll make a slight change where PagedResultsControl will not be sent if `paged` is `false` or `undefined`. 

Knowing all of this, if the library continues to return N-1 items, if you could please include a test for that, I can get things fixed up. 

Hope that helps!
