### ISSUE TITLE
Return empty attributes

### ISSUE THREAD

**Issue by tastypackets** [ldapts/ldapts#22]
It would be nice if all attributes requested that exist on the server were returned, instead of needing to check for keys to know if they are empty. Currently ldapts will remove attributes returned by the server that are falsy. (empty strings) Requesting a binary version still returns no keys if the value is falsy.

For example if you want a users phone number, but the `telephoneNumber` attribute was never filled in it will be empty and ldapts drops the attribute key.

```javascript
client.search('dc=domain,dc=local', {
        scope: 'sub',
        filter: `(userPrincipalName=testuser@domain.local)`,
        attributes: ['telephoneNumber']
      });

// Result [ { dn: 'CN=Test User,OU=Users,DC=domain,DC=local' } ]
```

For consistency it'd be nice to have:
```javascript
client.search('dc=domain,dc=local', {
        scope: 'sub',
        filter: `(userPrincipalName=testuser@domain.local)`,
        attributes: ['telephoneNumber']
      });

// Result [ { dn: 'CN=Test User,OU=Users,DC=domain,DC=local', telephoneNumber: ''} ]
```

It looks like this is happening on line 45 of SearchEntry.ts, however I didn't make any PR since I didn't know if this behavior was intentional.

**Comment by ma-zal** [comment]
I would like to ask, why empty attribute is filled by empty array `[]`? In the nice-to-have example you mentioned `telephoneNumber: ''`, that makes sense to me. But in reality for example when `mobile` attribute  is unfilled, it is returning `mobile: []`. Is this correct implementation, or bug? Personnaly I am expecting more the `null` value or empty string... not the empty array.

**Comment by jgeurts** [comment]
I originally wrote the search result attribute to mimic [how ldapjs handles attribute values](https://github.com/ldapjs/node-ldapjs/blob/master/lib/messages/search_entry.js#L48-L58). They return an empty array when there is no attribute value. 

Like ldapjs, for cases where an attribute only has one item in the array, we'll just take that single value.

From the [ldap v3 rfc](https://docs.ldap.com/specs/rfc4511.txt), a SearchResultEntry can return the DN of the entry and a `PartialAttributeList` for the attributes. The `PartialAttributeList` may hold zero elements. A `PartialAttribute` contains an array of strings or array of buffers for its value and the array can have zero values. 

I looked through a couple .net libraries and they seem to return arrays as well. But other libraries might handle things differently. 

I'm honestly not sure if it's ok to return `undefined` or an empty string instead of an empty array. I don't think I can do `null` since there's a specific ber encoding for null. I agree that the empty array is weird, but that might be the ldap way... ¯\_(ツ)_/¯

I'm open to suggestions if anyone can point to documentation that better describes things!
