### ISSUE TITLE
Determine if a client is still connected?

### ISSUE THREAD

**Issue by sarus** [ldapts/ldapts#25]
Is there a simple way to check prior to running a search operation whether or not an ldapts client is still connected and usable?  Specifically, I'm using ldapts in conjunction with a connection pool (node generic-pool) and I'm trying to find an efficient way to validate bound clients to see if they are still usable (e.g., to make sure the connection hasn't timed out due to being idle) after the connection is checked out from the pool.

Thank you!

**Comment by sarus** [comment]
Not sure how I missed this but looks like I can just use the `connected` flag on the client object.

Thanks!

**Comment by rgmz** [comment]
@sarus Wouldn't this issue still be relevant for TypeScript users since `connected` is private?

https://github.com/ldapts/ldapts/blob/63a657d93637c99345f024bd41ad3b92843f3d04/src/Client.ts#L142

**Comment by sarus** [comment]
@rgmz Hmm, good catch. Yes, I think this would still be an issue unless I'm missing some other way to check this.

**Comment by noah-alvarado** [comment]
I think rather than making `connected` a public field, we should just add a public getter. I've also used ldapts with generic-pool, and v3 made each `Pool`'s factory members want a function as their definition.

Plus every other field on Client is private...it almost feels wrong to make just one public haha
