### ISSUE TITLE
binding with empty bindDN and password

### ISSUE THREAD

**Issue by kvslee** [ldapts/ldapts#27]
```javascript
const { Client } = require('ldapts');

const url = 'ldap://ldap.forumsys.com:389';
const bindDN = '';
const password = '';

async function authenticate(bindDN, password) {
  const client = new Client({
    url,
  });

  let isAuthenticated;
    try {
      await client.bind(bindDN, password);
      isAuthenticated = true;
    } catch (ex) {
      isAuthenticated = false;
    } finally {
      await client.unbind();
    }
  return isAuthenticated;
}
```

I created a function with a given example. When bindDN and password are empty string, isAuthenticated returns true. I find that isAuthenticated in Try block gets assigned 'true'. In my understanding, await delays until client.bind function returns, right? If empty bindDN and password gets an error in binding, it should jumps into catch block. Any clue?

**Comment by jgeurts** [comment]
Some servers will allow an empty bindDN and password. It's called an anonymous bind. Unfortunately, I'm not able to have the forumsys or jumpcloud servers throw an error when I attempt an anonymous bind, so I can't really write a test for that case. But, my understanding is that if a server is configured to disallow anonymous binds, they should throw an `AuthMethodNotSupportedError` or similar. 

More details about the types of binds that are allowed can be found at: https://ldapwiki.com/wiki/Bind%20Request

Hope that helps!

Also, for what it's worth, subsequent calls should fail and throw since the user is not authenticated.

**Comment by bewue** [comment]
It also does **not** throw an error if bindDN is set and the password is empty. 

this is quite dangerous if you want to check login data of users. Is the behavior in this case also correct?
Or should I check the login data of users with another method?
