### ISSUE TITLE
Validate login of user.

### ISSUE THREAD

**Issue by wmantly** [ldapts/ldapts#78]
I am trying to use this project to log users in. After the system forms a bind, it needs to take the username and password provided by the user and validate it.

**Comment by jgeurts** [comment]
I'm not sure if you're asking a question or just letting me know how you're using the library :)

**Comment by wmantly** [comment]
I am asking a question, on how to properly use this library. My main use it to add LDAP backed login to my projects. I have set up a read-only bind user to perform operations on behalf of the system.

Now for my users, when they fill out the GUI login form, i need to validate they gave valid credentials. 
At this point, i need to unbind from the system bind user and with the user-provided credentials.

My questions is basically these;

1) To check if an application user's credentials are correct, is `client.bind()` the correct operation?

2) I am binding and unbinding all over my code. If this was python I would use a connection manager(`with`) to clean up the code. How would you recommend to clean the code up? Here is a sample of how I am using LDAP https://github.com/theta42/sso-manager-node/blob/master/nodejs/models/user_ldap.js

3) Is there a way to have my system bind user(lets say its cn=admin) perform LDAP actions on behalf of an application user? For instance, a user successfully logs in and wants to add another user to an LDAP group. That user attempts to add another user to an LDAP group they do not permission to edit. LDAP should not perform this action.

Thank you for taking the time to give me a hand. I appreciate any help or guidance i may receive.

**Comment by svenmuellerssen** [comment]
Hi @wmantly ,
I am searching for a library to communicate with a LDAP server and found this one. Because of your questions I was looking around in the code and found the _InvalidCredentialsError_. So I assume that you only have to use a _try...catch..._ block for the bind and catch this error if it fails because of wrong credentials. Maybe this solves your first question.

If I understand the context correct in your third question I would say that either permissions are part of the LDAP server itself or your application ensures permissions as part of the authorization. The library performs only requests without checking permissions.

Am I right?
Hope I was not completely wrong. :-)
